=== playtoncz/NESTv2/old/answers.dtd
<?xml version="1.0" encoding="windows-1250"?>
<!ELEMENT answers (case_description?, attribute*)>
 <!ELEMENT attribute (id, type, answer*)>
  <!ELEMENT answer (value?, weight?)>
  
<!ELEMENT case_description (#PCDATA)> <!-- string -->
<!ELEMENT id (#PCDATA)> <!-- string -->
<!ELEMENT type (#PCDATA)> <!-- binary | single | multiple | numeric -->
<!ELEMENT value (#PCDATA)> <!-- string or number (numeric) -->
<!ELEMENT weight  (#PCDATA)> <!-- number or "unknown"-->

=== playtoncz/NESTv2/tests/NestFormat.Tests/TestData/test_answers2.xml
<?xml version="1.0" encoding="windows-1250"?>
<!DOCTYPE answers SYSTEM "answers.dtd">
<answers>
 <case_description>test2_ans</case_description>
 <attribute>
  <id>bledost</id>
  <type>binary</type>
  <answer>
   <weight>0,667</weight>
  </answer>
 </attribute>
 <attribute>
  <id>dychavicnost</id>
  <type>binary</type>
  <answer>
   <weight>0,333</weight>
  </answer>
 </attribute>
 <attribute>
  <id>teplota</id>
  <type>numeric</type>
  <answer>
   <value>39,000</value>
  </answer>
 </attribute>
 <attribute>
  <id>priznaky</id>
  <type>multiple</type>
  <answer>
   <value>kasel</value>
   <weight>1,000</weight>
  </answer>
 </attribute>
</answers>
