=== playtoncz/NESTv2/old/base.dtd
<?xml version="1.0" encoding="windows-1250"?>
<!ELEMENT base (global, attributes, contexts?, rules?, integrity_constraints?, system_info?)>
<!ELEMENT global (description?, expert?, knowledge_engineer?, date?, inference_mechanism, weight_range, 
                 default_weight, global_priority, context_global_threshold, condition_global_threshold)>
<!ELEMENT attributes (attribute*)>
  <!ELEMENT attribute (id, name?, type, scope?, id_context?, context_threshold?, legal_values?, sources?,
                      comment?, actions?, propositions?)>
    <!ELEMENT legal_values ((lower_bound?, upper_bound?)|(value+))>
    <!ELEMENT sources (source+)>
     <!ELEMENT source (source_type, source_file?, source_file_delete?, function?, parameters?, calculation?, default_weight?)>
      <!ELEMENT calculation (expression+)>
       <!ELEMENT expression (entry1, entry2, operand)>
    <!ELEMENT actions (action+)>
      <!ELEMENT action (function, parameters?, action_threshold?)>
    <!ELEMENT propositions (proposition+)>
      <!ELEMENT proposition (id, name?, weight_function?, comment?, actions?)>
        <!ELEMENT weight_function ((weight_value+)|(fuzzy_lower_bound, crisp_lower_bound, crisp_upper_bound, fuzzy_upper_bound))>
          <!ELEMENT weight_value (name, weight)>
<!ELEMENT contexts (context*)>
  <!ELEMENT context (id, comment?, condition)>
    <!ELEMENT condition (conjunction+)>
      <!ELEMENT conjunction (literal+)>
        <!ELEMENT literal (id_attribute, id_proposition?, negation)>
<!ELEMENT rules (apriori_rules?, logical_rules?, compositional_rules?)>
  <!ELEMENT apriori_rules (apriori_rule*)>
    <!ELEMENT apriori_rule (id, priority?, conclusions, comment?, actions?)>
      <!ELEMENT conclusions (conclusion+)>
        <!ELEMENT conclusion (id_attribute, id_proposition?, negation, weight?)>
  <!ELEMENT logical_rules (logical_rule*)>
    <!ELEMENT logical_rule (id, priority?, id_context?, context_threshold?, condition_threshold?, condition, conclusions, comment?, actions?)>
  <!ELEMENT compositional_rules (compositional_rule*)>
    <!ELEMENT compositional_rule (id, priority?, id_context?, context_threshold?, condition_threshold?, condition, conclusions, comment?, actions?)>
  <!ELEMENT integrity_constraints (integrity_constraint*)>
    <!ELEMENT integrity_constraint (id, name?, id_context?, context_threshold?, condition, conclusions, comment?)>
  
<!ELEMENT action_threshold (#PCDATA)> <!-- number -->
<!ELEMENT comment (#PCDATA)> <!-- string -->
<!ELEMENT condition_global_threshold (#PCDATA)> <!-- number -->
<!ELEMENT condition_threshold (#PCDATA)> <!-- number -->
<!ELEMENT context_global_threshold (#PCDATA)> <!-- number -->
<!ELEMENT context_threshold (#PCDATA)> <!-- number -->
<!ELEMENT crisp_lower_bound (#PCDATA)> <!-- number -->
<!ELEMENT crisp_upper_bound (#PCDATA)> <!-- number -->
<!ELEMENT date (#PCDATA)>  <!-- date -->
<!ELEMENT default_weight (#PCDATA)> <!-- unknown | irrelevant -->
<!ELEMENT description (#PCDATA)> <!-- string -->
<!ELEMENT entry1 (#PCDATA)> <!-- string -->
<!ELEMENT entry2 (#PCDATA)> <!-- string -->
<!ELEMENT expert (#PCDATA)> <!-- string -->
<!ELEMENT function (#PCDATA)> <!-- exe file with function -->
<!ELEMENT fuzzy_lower_bound (#PCDATA)> <!-- number -->
<!ELEMENT fuzzy_upper_bound (#PCDATA)> <!--number -->
<!ELEMENT global_priority (#PCDATA)> <!-- first | last | minlength | maxlength | user -->
<!ELEMENT id (#PCDATA)> <!-- string -->
<!ELEMENT id_attribute (#PCDATA)> <!-- string -->
<!ELEMENT id_context (#PCDATA)> <!-- string -->
<!ELEMENT id_proposition (#PCDATA)> <!-- string -->
<!ELEMENT inference_mechanism (#PCDATA)> <!-- standard | logical | neuronal | hybrid -->
<!ELEMENT knowledge_engineer (#PCDATA)> <!-- string -->
<!ELEMENT lower_bound (#PCDATA)> <!-- number -->
<!ELEMENT name (#PCDATA)> <!-- string -->
<!ELEMENT negation (#PCDATA)> <!-- -1 : true, 0 : false -->
<!ELEMENT operand (#PCDATA)> <!-- 1 | 2 | 3| 4 -->
<!ELEMENT parameters (#PCDATA)> <!-- string -->
<!ELEMENT priority (#PCDATA)> <!-- number from <0;1> -->
<!ELEMENT scope (#PCDATA)> <!-- case | environment -->
<!ELEMENT source_file (#PCDATA)> <!-- string -->
<!ELEMENT source_file_delete (#PCDATA)> <!-- boolean (0;1) -->
<!ELEMENT source_type (#PCDATA)> <!-- infer | user | external_file | external_function | calc | default_weight -->
<!ELEMENT source_weight (#PCDATA)> <!-- weight -->
<!ELEMENT type (#PCDATA)> <!-- binary | single | multiple | numeric -->
<!ELEMENT upper_bound (#PCDATA)> <!-- number -->
<!ELEMENT value (#PCDATA)> <!-- string -->
<!ELEMENT weight (#PCDATA)> <!-- number -->
<!ELEMENT weight_range (#PCDATA)> <!-- number -->



<!ELEMENT system_info (nest:options?)> 
<!ELEMENT nest:options (nest:version?)>
  <!ATTLIST nest:options xmlns:nest CDATA #FIXED "http://lisp.vse.cz/NEST">
<!ELEMENT nest:version (#PCDATA)> <!-- string -->

<!-- version: 1.3.0 -->

=== playtoncz/NESTv2/old/NestWeb/BZ/Princ_u.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE base SYSTEM "base.dtd">
<base>

<!--******************** Global properties ********************-->

 <global>
  <description>Princ</description>
  <expert>PB</expert>
  <date>4.6.2003</date>
  <inference_mechanism>standard</inference_mechanism>
  <weight_range>3</weight_range>
  <default_weight>irrelevant</default_weight>
  <global_priority>first</global_priority>
  <context_global_threshold>1,500</context_global_threshold>
  <condition_global_threshold>0,000</condition_global_threshold>
 </global>

<!--******************** Attributes and propositions ********************-->

 <attributes>

  <attribute>
   <id>princ</id>
   <name>Princ</name>
   <type>binary</type>
   <comment>Jedná se o prince?</comment>
  </attribute>

  <attribute>
   <id>velikost_nohy</id>
   <name>jakou ma adept velikost nohy</name>
   <type>numeric</type>
   <legal_values>
    <lower_bound>0,000</lower_bound>
    <upper_bound>50,000</upper_bound>
   </legal_values>
   <comment>princ musi mit malou nozku</comment>
   <propositions>
    <proposition>
     <id>malá_noha</id>
     <name>Malá noha</name>
     <weight_function>
      <fuzzy_lower_bound>0,000</fuzzy_lower_bound>
      <crisp_lower_bound>0,000</crisp_lower_bound>
      <crisp_upper_bound>39,000</crisp_upper_bound>
      <fuzzy_upper_bound>41,000</fuzzy_upper_bound>
     </weight_function>
    </proposition>
    <proposition>
     <id>střední_noha</id>
     <name>Střední noha</name>
     <weight_function>
      <fuzzy_lower_bound>39,000</fuzzy_lower_bound>
      <crisp_lower_bound>41,000</crisp_lower_bound>
      <crisp_upper_bound>42,000</crisp_upper_bound>
      <fuzzy_upper_bound>44,000</fuzzy_upper_bound>
     </weight_function>
    </proposition>
    <proposition>
     <id>velká_noha</id>
     <name>Velká noha</name>
     <weight_function>
      <fuzzy_lower_bound>42,000</fuzzy_lower_bound>
      <crisp_lower_bound>44,000</crisp_lower_bound>
      <crisp_upper_bound>50,000</crisp_upper_bound>
      <fuzzy_upper_bound>50,000</fuzzy_upper_bound>
     </weight_function>
    </proposition>
   </propositions>
  </attribute>

  <attribute>
   <id>dobrá_rodina</id>
   <name>dobrá rodina</name>
   <type>binary</type>
   <comment>Princ musí pocházet z dobré rodiny</comment>
  </attribute>

  <attribute>
   <id>modrá_krev</id>
   <name>Modrá krev</name>
   <type>binary</type>
   <comment>Šlechtici musí mít modrou krev</comment>
  </attribute>

  <attribute>
   <id>bohatá_rodina</id>
   <name>Bohatá rodina</name>
   <type>binary</type>
   <comment>Princ musí být z bohaté rodiny</comment>
  </attribute>

  <attribute>
   <id>majetek</id>
   <type>multiple</type>
   <propositions>
    <proposition>
     <id>penize</id>
     <name>majetek(penize)</name>
    </proposition>
    <proposition>
     <id>pozemky</id>
     <name>majetek(pozemky)</name>
    </proposition>
   </propositions>
  </attribute>
 </attributes>

<!--******************** Contexts ********************-->

 <contexts>

  <context>
   <id>CTX1</id>
   <condition>
    <conjunction>
     <literal>
      <id_attribute>velikost_nohy</id_attribute>
      <id_proposition>malá_noha</id_proposition>
      <negation>0</negation>
     </literal>
    </conjunction>
   </condition>
  </context>
 </contexts>

<!--******************** Rules ********************-->

 <rules>

<!--******************** Apriori rules ********************-->

  <apriori_rules>
  </apriori_rules>

<!--******************** Logical rules ********************-->

  <logical_rules>

   <logical_rule>
    <id>l1</id>
    <condition>
    <conjunction>
     <literal>
      <id_attribute>velikost_nohy</id_attribute>
      <id_proposition>velká_noha</id_proposition>
      <negation>0</negation>
     </literal>
    </conjunction>
    <conjunction>
     <literal>
      <id_attribute>velikost_nohy</id_attribute>
      <id_proposition>střední_noha</id_proposition>
      <negation>0</negation>
     </literal>
    </conjunction>
    </condition>
    <conclusions>
     <conclusion>
      <id_attribute>princ</id_attribute>
      <negation>1</negation>
     </conclusion>
    </conclusions>
   </logical_rule>

   <logical_rule>
    <id>l2</id>
    <id_context>CTX1</id_context>
    <context_threshold>0,500</context_threshold>
    <condition>
    <conjunction>
     <literal>
      <id_attribute>dobrá_rodina</id_attribute>
      <negation>1</negation>
     </literal>
    </conjunction>
    </condition>
    <conclusions>
     <conclusion>
      <id_attribute>princ</id_attribute>
      <negation>1</negation>
     </conclusion>
    </conclusions>
   </logical_rule>

   <logical_rule>
    <id>l3</id>
    <condition>
    <conjunction>
     <literal>
      <id_attribute>modrá_krev</id_attribute>
      <negation>1</negation>
     </literal>
    </conjunction>
    <conjunction>
     <literal>
      <id_attribute>bohatá_rodina</id_attribute>
      <negation>1</negation>
     </literal>
    </conjunction>
    </condition>
    <conclusions>
     <conclusion>
      <id_attribute>dobrá_rodina</id_attribute>
      <negation>1</negation>
     </conclusion>
    </conclusions>
   </logical_rule>

   <logical_rule>
    <id>l4</id>
    <condition>
    <conjunction>
     <literal>
      <id_attribute>majetek</id_attribute>
      <id_proposition>penize</id_proposition>
      <negation>1</negation>
     </literal>
     <literal>
      <id_attribute>majetek</id_attribute>
      <id_proposition>pozemky</id_proposition>
      <negation>1</negation>
     </literal>
    </conjunction>
    </condition>
    <conclusions>
     <conclusion>
      <id_attribute>bohatá_rodina</id_attribute>
      <negation>1</negation>
     </conclusion>
    </conclusions>
   </logical_rule>
  </logical_rules>

<!--******************** Compositional rules ********************-->

  <compositional_rules>

   <compositional_rule>
    <id>c1</id>
    <condition>
    <conjunction>
     <literal>
      <id_attribute>velikost_nohy</id_attribute>
      <id_proposition>malá_noha</id_proposition>
      <negation>0</negation>
     </literal>
     <literal>
      <id_attribute>dobrá_rodina</id_attribute>
      <negation>0</negation>
     </literal>
    </conjunction>
    </condition>
    <conclusions>
     <conclusion>
      <id_attribute>princ</id_attribute>
      <negation>0</negation>
      <weight>3,000</weight>
     </conclusion>
    </conclusions>
   </compositional_rule>

   <compositional_rule>
    <id>c2</id>
    <condition>
    <conjunction>
     <literal>
      <id_attribute>modrá_krev</id_attribute>
      <negation>0</negation>
     </literal>
     <literal>
      <id_attribute>bohatá_rodina</id_attribute>
      <negation>0</negation>
     </literal>
    </conjunction>
    </condition>
    <conclusions>
     <conclusion>
      <id_attribute>dobrá_rodina</id_attribute>
      <negation>0</negation>
      <weight>3,000</weight>
     </conclusion>
    </conclusions>
   </compositional_rule>

   <compositional_rule>
    <id>c3</id>
    <condition>
    <conjunction>
     <literal>
      <id_attribute>majetek</id_attribute>
      <id_proposition>penize</id_proposition>
      <negation>0</negation>
     </literal>
    </conjunction>
    <conjunction>
     <literal>
      <id_attribute>majetek</id_attribute>
      <id_proposition>pozemky</id_proposition>
      <negation>0</negation>
     </literal>
    </conjunction>
    </condition>
    <conclusions>
     <conclusion>
      <id_attribute>bohatá_rodina</id_attribute>
      <negation>0</negation>
      <weight>3,000</weight>
     </conclusion>
    </conclusions>
   </compositional_rule>
  </compositional_rules>
 </rules>

<!--******************** Integrity constraints ********************-->

 <integrity_constraints>
 </integrity_constraints>
 <system_info>
  <nest:options xmlns:nest="http://lisp.vse.cz/NEST">
   <nest:version>2.0.3</nest:version>
  </nest:options>
 </system_info>
</base>

=== playtoncz/NESTv2/old/NestWeb/BZ_en/Prince.xml
<?xml version="1.0" encoding="windows-1250"?>
<!DOCTYPE base SYSTEM "base.dtd">
<base>
 <global>
  <description>Prince</description>
  <expert>PB</expert>
  <date>4.6.2003</date>
  <inference_mechanism>standard</inference_mechanism>
  <weight_range>3</weight_range>
  <default_weight>irrelevant</default_weight>
  <global_priority>first</global_priority>
  <context_global_threshold>1,500</context_global_threshold>
  <condition_global_threshold>0,000</condition_global_threshold>
 </global>
 <attributes>
  <attribute>
   <id>prince</id>
   <name>Prince</name>
   <type>binary</type>
   <comment>Is it a prince?</comment>
  </attribute>
  <attribute>
   <id>size_of_foot</id>
   <name>What is the size of adept's foot?</name>
   <type>numeric</type>
   <legal_values>
    <lower_bound>0,000</lower_bound>
    <upper_bound>50,000</upper_bound>
   </legal_values>
   <comment>Prince has to have small foot.</comment>
   <propositions>
    <proposition>
     <id>small_foot</id>
     <name>Small foot</name>
     <weight_function>
      <fuzzy_lower_bound>0,000</fuzzy_lower_bound>
      <crisp_lower_bound>0,000</crisp_lower_bound>
      <crisp_upper_bound>39,000</crisp_upper_bound>
      <fuzzy_upper_bound>41,000</fuzzy_upper_bound>
     </weight_function>
    </proposition>
    <proposition>
     <id>medium_foot</id>
     <name>Medium foot</name>
     <weight_function>
      <fuzzy_lower_bound>39,000</fuzzy_lower_bound>
      <crisp_lower_bound>41,000</crisp_lower_bound>
      <crisp_upper_bound>42,000</crisp_upper_bound>
      <fuzzy_upper_bound>44,000</fuzzy_upper_bound>
     </weight_function>
    </proposition>
    <proposition>
     <id>big_foot</id>
     <name>Big foot</name>
     <weight_function>
      <fuzzy_lower_bound>42,000</fuzzy_lower_bound>
      <crisp_lower_bound>44,000</crisp_lower_bound>
      <crisp_upper_bound>50,000</crisp_upper_bound>
      <fuzzy_upper_bound>50,000</fuzzy_upper_bound>
     </weight_function>
    </proposition>
   </propositions>
  </attribute>
  <attribute>
   <id>good_family</id>
   <name>good family</name>
   <type>binary</type>
   <comment>Prince has to be from good family</comment>
  </attribute>
  <attribute>
   <id>blue_blood</id>
   <name>Blue blood</name>
   <type>binary</type>
   <comment>Aristrocrat has to have blue blood</comment>
  </attribute>
  <attribute>
   <id>wealthy_family</id>
   <name>Wealthy family</name>
   <type>binary</type>
   <comment>Prince has to come from wealthy family</comment>
  </attribute>
  <attribute>
   <id>property</id>
   <name>Property</name>
   <type>multiple</type>
   <propositions>
    <proposition>
     <id>money</id>
     <name>Money</name>
    </proposition>
    <proposition>
     <id>lots</id>
     <name>Lots</name>
    </proposition>
   </propositions>
  </attribute>
 </attributes>
 <contexts>
  <context>
   <id>CTX1</id>
   <condition>
    <conjunction>
     <literal>
      <id_attribute>size_of_foot</id_attribute>
      <id_proposition>small_foot</id_proposition>
      <negation>0</negation>
     </literal>
    </conjunction>
   </condition>
  </context>
 </contexts>
 <rules>
  <apriori_rules>
  </apriori_rules>
  <logical_rules>
   <logical_rule>
    <id>l1</id>
    <condition>
    <conjunction>
     <literal>
      <id_attribute>size_of_foot</id_attribute>
      <id_proposition>big_foot</id_proposition>
      <negation>0</negation>
     </literal>
    </conjunction>
    <conjunction>
     <literal>
      <id_attribute>size_of_foot</id_attribute>
      <id_proposition>medium_foot</id_proposition>
      <negation>0</negation>
     </literal>
    </conjunction>
    </condition>
    <conclusions>
     <conclusion>
      <id_attribute>prince</id_attribute>
      <negation>1</negation>
     </conclusion>
    </conclusions>
   </logical_rule>
   <logical_rule>
    <id>l2</id>
    <id_context>CTX1</id_context>
    <context_threshold>0,500</context_threshold>
    <condition>
    <conjunction>
     <literal>
      <id_attribute>good_family</id_attribute>
      <negation>1</negation>
     </literal>
    </conjunction>
    </condition>
    <conclusions>
     <conclusion>
      <id_attribute>prince</id_attribute>
      <negation>1</negation>
     </conclusion>
    </conclusions>
   </logical_rule>
   <logical_rule>
    <id>l3</id>
    <condition>
    <conjunction>
     <literal>
      <id_attribute>blue_blood</id_attribute>
      <negation>1</negation>
     </literal>
    </conjunction>
    <conjunction>
     <literal>
      <id_attribute>wealthy_family</id_attribute>
      <negation>1</negation>
     </literal>
    </conjunction>
    </condition>
    <conclusions>
     <conclusion>
      <id_attribute>good_family</id_attribute>
      <negation>1</negation>
     </conclusion>
    </conclusions>
   </logical_rule>
   <logical_rule>
    <id>l4</id>
    <condition>
    <conjunction>
     <literal>
      <id_attribute>property</id_attribute>
      <id_proposition>money</id_proposition>
      <negation>1</negation>
     </literal>
     <literal>
      <id_attribute>property</id_attribute>
      <id_proposition>lots</id_proposition>
      <negation>1</negation>
     </literal>
    </conjunction>
    </condition>
    <conclusions>
     <conclusion>
      <id_attribute>wealthy_family</id_attribute>
      <negation>1</negation>
     </conclusion>
    </conclusions>
   </logical_rule>
  </logical_rules>
  <compositional_rules>
   <compositional_rule>
    <id>c1</id>
    <condition>
    <conjunction>
     <literal>
      <id_attribute>size_of_foot</id_attribute>
      <id_proposition>small_foot</id_proposition>
      <negation>0</negation>
     </literal>
     <literal>
      <id_attribute>good_family</id_attribute>
      <negation>0</negation>
     </literal>
    </conjunction>
    </condition>
    <conclusions>
     <conclusion>
      <id_attribute>prince</id_attribute>
      <negation>0</negation>
      <weight>3,000</weight>
     </conclusion>
    </conclusions>
   </compositional_rule>
   <compositional_rule>
    <id>c2</id>
    <condition>
    <conjunction>
     <literal>
      <id_attribute>blue_blood</id_attribute>
      <negation>0</negation>
     </literal>
     <literal>
      <id_attribute>wealthy_family</id_attribute>
      <negation>0</negation>
     </literal>
    </conjunction>
    </condition>
    <conclusions>
     <conclusion>
      <id_attribute>good_family</id_attribute>
      <negation>0</negation>
      <weight>3,000</weight>
     </conclusion>
    </conclusions>
   </compositional_rule>
   <compositional_rule>
    <id>c3</id>
    <condition>
    <conjunction>
     <literal>
      <id_attribute>property</id_attribute>
      <id_proposition>money</id_proposition>
      <negation>0</negation>
     </literal>
    </conjunction>
    <conjunction>
     <literal>
      <id_attribute>property</id_attribute>
      <id_proposition>lots</id_proposition>
      <negation>0</negation>
     </literal>
    </conjunction>
    </condition>
    <conclusions>
     <conclusion>
      <id_attribute>wealthy_family</id_attribute>
      <negation>0</negation>
      <weight>3,000</weight>
     </conclusion>
    </conclusions>
   </compositional_rule>
  </compositional_rules>
 </rules>
 <integrity_constraints>
 </integrity_constraints>
 <system_info>
  <nest:options xmlns:nest="http://lisp.vse.cz/NEST">
   <nest:version>1.2.4</nest:version>
  </nest:options>
 </system_info>
</base>

=== playtoncz/NESTv2/old/NestFileClient/NestFileClient/bin/Debug/BZ.xml
<?xml version="1.0" encoding="windows-1250"?>
<!DOCTYPE base SYSTEM "base.dtd">
<base>

<!--******************** Global properties ********************-->

 <global>
  <description>Nemoci1</description>
  <expert>PB</expert>
  <date>4.6.2003</date>
  <inference_mechanism>logical</inference_mechanism>
  <weight_range>3</weight_range>
  <default_weight>unknown</default_weight>
  <global_priority>first</global_priority>
  <context_global_threshold>0,000</context_global_threshold>
  <condition_global_threshold>0,000</condition_global_threshold>
 </global>

<!--******************** Attributes and propositions ********************-->

 <attributes>

  <attribute>
   <id>diagnoza</id>
   <type>multiple</type>
   <propositions>
    <proposition>
     <id>Nachlazeni</id>
    </proposition>
    <proposition>
     <id>Chripka</id>
    </proposition>
    <proposition>
     <id>TBC</id>
    </proposition>
   </propositions>
  </attribute>

  <attribute>
   <id>bledost</id>
   <name>pacient je bledy</name>
   <type>binary</type>
  </attribute>

  <attribute>
   <id>dychavicnost</id>
   <type>binary</type>
  </attribute>

  <attribute>
   <id>plice</id>
   <type>binary</type>
  </attribute>

  <attribute>
   <id>HCD</id>
   <type>binary</type>
  </attribute>

  <attribute>
   <id>teplota</id>
   <name>teplota pacienta</name>
   <type>numeric</type>
   <legal_values>
    <lower_bound>35,000</lower_bound>
    <upper_bound>42,000</upper_bound>
   </legal_values>
   <propositions>
    <proposition>
     <id>normalni</id>
     <name>pacient ma normalni teplotu</name>
     <weight_function>
      <fuzzy_lower_bound>35,000</fuzzy_lower_bound>
      <crisp_lower_bound>35,000</crisp_lower_bound>
      <crisp_upper_bound>36,800</crisp_upper_bound>
      <fuzzy_upper_bound>37,500</fuzzy_upper_bound>
     </weight_function>
    </proposition>
    <proposition>
     <id>zvysena</id>
     <name>pacient ma zvysenou teplotu</name>
     <weight_function>
      <fuzzy_lower_bound>36,500</fuzzy_lower_bound>
      <crisp_lower_bound>37,500</crisp_lower_bound>
      <crisp_upper_bound>42,000</crisp_upper_bound>
      <fuzzy_upper_bound>42,000</fuzzy_upper_bound>
     </weight_function>
    </proposition>
   </propositions>
  </attribute>

  <attribute>
   <id>priznaky</id>
   <name>dalsi priznaky</name>
   <type>multiple</type>
   <propositions>
    <proposition>
     <id>kasel</id>
    </proposition>
    <proposition>
     <id>ryma</id>
    </proposition>
   </propositions>
  </attribute>
 </attributes>

<!--******************** Contexts ********************-->

 <contexts>
 </contexts>

<!--******************** Rules ********************-->

 <rules>

<!--******************** Apriori rules ********************-->

  <apriori_rules>
  </apriori_rules>

<!--******************** Logical rules ********************-->

  <logical_rules>
  </logical_rules>

<!--******************** Compositional rules ********************-->

  <compositional_rules>

   <compositional_rule>
    <id>c1</id>
    <condition>
    <conjunction>
     <literal>
      <id_attribute>bledost</id_attribute>
      <negation>0</negation>
     </literal>
    </conjunction>
    </condition>
    <conclusions>
     <conclusion>
      <id_attribute>diagnoza</id_attribute>
      <id_proposition>TBC</id_proposition>
      <negation>0</negation>
      <weight>1,000</weight>
     </conclusion>
    </conclusions>
   </compositional_rule>

   <compositional_rule>
    <id>c2</id>
    <condition>
    <conjunction>
     <literal>
      <id_attribute>dychavicnost</id_attribute>
      <negation>0</negation>
     </literal>
    </conjunction>
    </condition>
    <conclusions>
     <conclusion>
      <id_attribute>plice</id_attribute>
      <negation>0</negation>
      <weight>2,000</weight>
     </conclusion>
    </conclusions>
   </compositional_rule>

   <compositional_rule>
    <id>c3</id>
    <condition>
    <conjunction>
     <literal>
      <id_attribute>priznaky</id_attribute>
      <id_proposition>kasel</id_proposition>
      <negation>0</negation>
     </literal>
    </conjunction>
    </condition>
    <conclusions>
     <conclusion>
      <id_attribute>plice</id_attribute>
      <negation>0</negation>
      <weight>2,000</weight>
     </conclusion>
    </conclusions>
   </compositional_rule>

   <compositional_rule>
    <id>c4</id>
    <condition>
    <conjunction>
     <literal>
      <id_attribute>priznaky</id_attribute>
      <id_proposition>kasel</id_proposition>
      <negation>0</negation>
     </literal>
    </conjunction>
    </condition>
    <conclusions>
     <conclusion>
      <id_attribute>HCD</id_attribute>
      <negation>0</negation>
      <weight>3,000</weight>
     </conclusion>
    </conclusions>
   </compositional_rule>

   <compositional_rule>
    <id>c5</id>
    <condition>
    <conjunction>
     <literal>
      <id_attribute>priznaky</id_attribute>
      <id_proposition>ryma</id_proposition>
      <negation>0</negation>
     </literal>
    </conjunction>
    </condition>
    <conclusions>
     <conclusion>
      <id_attribute>HCD</id_attribute>
      <negation>0</negation>
      <weight>2,000</weight>
     </conclusion>
    </conclusions>
   </compositional_rule>

   <compositional_rule>
    <id>c6</id>
    <condition>
    <conjunction>
     <literal>
      <id_attribute>plice</id_attribute>
      <negation>0</negation>
     </literal>
    </conjunction>
    </condition>
    <conclusions>
     <conclusion>
      <id_attribute>diagnoza</id_attribute>
      <id_proposition>TBC</id_proposition>
      <negation>0</negation>
      <weight>2,000</weight>
     </conclusion>
    </conclusions>
   </compositional_rule>

   <compositional_rule>
    <id>c7</id>
    <condition>
    <conjunction>
     <literal>
      <id_attribute>HCD</id_attribute>
      <negation>0</negation>
     </literal>
     <literal>
      <id_attribute>teplota</id_attribute>
      <id_proposition>zvysena</id_proposition>
      <negation>0</negation>
     </literal>
    </conjunction>
    </condition>
    <conclusions>
     <conclusion>
      <id_attribute>diagnoza</id_attribute>
      <id_proposition>Chripka</id_proposition>
      <negation>0</negation>
      <weight>3,000</weight>
     </conclusion>
    </conclusions>
   </compositional_rule>

   <compositional_rule>
    <id>c8</id>
    <condition>
    <conjunction>
     <literal>
      <id_attribute>HCD</id_attribute>
      <negation>0</negation>
     </literal>
     <literal>
      <id_attribute>teplota</id_attribute>
      <id_proposition>normalni</id_proposition>
      <negation>0</negation>
     </literal>
    </conjunction>
    </condition>
    <conclusions>
     <conclusion>
      <id_attribute>diagnoza</id_attribute>
      <id_proposition>Nachlazeni</id_proposition>
      <negation>0</negation>
      <weight>3,000</weight>
     </conclusion>
    </conclusions>
   </compositional_rule>
  </compositional_rules>
 </rules>

<!--******************** Integrity constraints ********************-->

 <integrity_constraints>
 </integrity_constraints>
 <system_info>
  <nest:options xmlns:nest="http://lisp.vse.cz/NEST">
   <nest:version>2.0.4</nest:version>
  </nest:options>
 </system_info>
</base>
